local colors = require('base46').get_colors('base_30')

return {
  Comment = { fg = colors.grey_fg },
  CursorLineNr = { fg = colors.white },
  LineNr = { fg = colors.grey },
  EndOfBuffer = { fg = colors.black },
  FloatBorder = { fg = colors.line },
  NormalFloat = { bg = colors.black },
  Normal = { bg = colors.black },
  --PmenuSel = { bg = colors.pmenu_bg, fg = colors.black },
  --Pmenu = { bg = colors.darker_black },
  --PmenuSbar = { bg = colors.black2 },
  --PmenuThumb = { bg = colors.darker_black },
  Pmenu = { bg = colors.black },
  PmenuSbar = { bg = colors.one_bg },
  PmenuSel = { bg = colors.pmenu_bg, fg = colors.black },
  PmenuThumb = { bg = colors.grey },
  NvimInternalError = { fg = colors.red },
  WinSeparator = { fg = colors.line },
  AlphaHeader = { fg = colors.grey_fg },
  AlphaButtons = { fg = colors.light_grey },
  LspReferenceText = { fg = colors.darker_black, bg = colors.white },
  LspReferenceRead = { fg = colors.darker_black, bg = colors.white },
  LspReferenceWrite = { fg = colors.darker_black, bg = colors.white },
  IndentBlanklineChar = { fg = colors.line },
  IndentBlanklineSpaceChar = { fg = colors.line },
  DiagnosticHint = { fg = colors.purple },
  DiagnosticError = { fg = colors.red },
  DiagnosticWarn = { fg = colors.yellow },
  DiagnosticInformation = { fg = colors.vibrant_green },
  WhichKey = { fg = colors.blue },
  WhichKeySeparator = { fg = colors.light_grey },
  WhichKeyDesc = { fg = colors.red },
  WhichKeyGroup = { fg = colors.green },
  WhichKeyValue = { fg = colors.green },
  PackerPackageName = { fg = colors.red },
  PackerSuccess = { fg = colors.green },
  PackerProgress = { fg = colors.blue },
  PackerOutput = { fg = colors.red },
  PackerStatus = { fg = colors.blue },
  MatchWord = { fg = colors.orange, bold = true },
  MatchParen = { link = 'MatchWord' },
  MatchWordCur = {},
  MatchParenCur = { link = 'MatchWordCur' },
}
