local base16 = require('base46').get_colors('base_16')
local colors = require('base46').get_colors('base_30')

return {
  -- nvim Navic
  NavicAbbr = { fg = colors.white, bg = colors.statusline_bg, bold = true },
  NavicAbbrMatch = { fg = colors.blue, bold = true, bg = colors.statusline_bg },
  NavicBorder = { fg = colors.grey, bg = colors.statusline_bg, bold = true },
  NavicDocBorder = { fg = colors.grey, bg = colors.statusline_bg, bold = true },

  -- Navic item kinds
  NavicConstant = { fg = base16.base09, bg = colors.statusline_bg, bold = true },
  NavicFunction = { fg = base16.base0D, bg = colors.statusline_bg, bold = true },
  NavicIdentifier = { fg = base16.base08, bg = colors.statusline_bg, bold = true },
  NavicField = { fg = base16.base08, bg = colors.statusline_bg, bold = true },
  NavicVariable = { fg = base16.base0E, bg = colors.statusline_bg, bold = true },
  NavicSnippet = { fg = colors.red, bg = colors.statusline_bg, bold = true },
  NavicText = { fg = base16.base0B, bg = colors.statusline_bg, bold = true },
  NavicStructure = { fg = base16.base0E, bg = colors.statusline_bg, bold = true },
  NavicType = { fg = base16.base0A, bg = colors.statusline_bg, bold = true },
  NavicKeyword = { fg = base16.base07, bg = colors.statusline_bg, bold = true },
  NavicMethod = { fg = base16.base0D, bg = colors.statusline_bg, bold = true },
  NavicConstructor = { fg = colors.blue, bg = colors.statusline_bg, bold = true },
  NavicFolder = { fg = base16.base07, bg = colors.statusline_bg, bold = true },
  NavicModule = { fg = base16.base0A, bg = colors.statusline_bg, bold = true },
  NavicProperty = { fg = base16.base08, bg = colors.statusline_bg, bold = true },
  NavicEnum = { fg = '', bg = colors.statusline_bg, bold = true },
  NavicUnit = { fg = base16.base0E, bg = colors.statusline_bg, bold = true },
  NavicClass = { fg = '', bg = colors.statusline_bg, bold = true },
  NavicFile = { fg = base16.base07, bg = colors.statusline_bg, bold = true },
  NavicInterface = { fg = '', bg = colors.statusline_bg, bold = true },
  NavicColor = { fg = colors.red, bg = colors.statusline_bg, bold = true },
  NavicReference = { fg = base16.base05, bg = colors.statusline_bg, bold = true },
  NavicEnumMember = { fg = '', bg = colors.statusline_bg, bold = true },
  NavicStruct = { fg = base16.base0E, bg = colors.statusline_bg, bold = true },
  NavicValue = { fg = '', bg = colors.statusline_bg, bold = true },
  NavicEvent = { fg = '', bg = colors.statusline_bg, bold = true },
  NavicOperator = { fg = base16.base05, bg = colors.statusline_bg, bold = true },
  NavicTypeParameter = { fg = base16.base08, bg = colors.statusline_bg, bold = true },

  NavicIconsFile = { link = 'CmpItemKindFile' },
  NavicIconsModule = { link = 'CmpItemKindClass' },
  NavicIconsNamespace = { link = 'CmpItemKindClass' },
  NavicIconsPackage = { link = 'CmpItemKindProperty' },
  NavicIconsClass = { link = 'CmpItemKindClass' },
  NavicIconsMethod = { link = 'CmpItemKindMethod' },
  NavicIconsProperty = { link = 'CmpItemKindProperty' },
  NavicIconsField = { link = 'CmpItemKindField' },
  NavicIconsConstructor = { link = 'CmpItemKindConstructor' },
  NavicIconsEnum = { link = 'CmpItemKindValue' },
  NavicIconsInterface = { link = 'CmpItemKindInterface' },
  NavicIconsFunction = { link = 'CmpItemKindFunction' },
  NavicIconsVariable = { default = true, link = 'CmpItemKindVariable' },
  NavicIconsConstant = { link = 'CmpItemKindVariable' },
  NavicIconsString = { link = 'CmpItemKindText' },
  NavicIconsNumber = { link = 'CmpItemKindValue' },
  NavicIconsBoolean = { link = 'CmpItemKindValue' },
  NavicIconsArray = { link = 'CmpItemKindVariable' },
  NavicIconsObject = { link = 'CmpItemKindVariable' },
  NavicIconsKey = { link = 'CmpItemKindKeyword' },
  NavicIconsNull = { link = 'TSNone' },
  NavicIconsEnumMember = { link = 'CmpItemKindVariable' },
  NavicIconsStruct = { link = 'CmpItemKindStruct' },
  NavicIconsEvent = { link = 'CmpItemKindEvent' },
  NavicIconsOperator = { link = 'CmpItemKindOperator' },
  NavicIconsTypeParameter = { link = 'CmpItemKindTypeParameter' },
  NavicIconsText = { link = 'CmpItemKindText' },
  NavicIconsSeparator = { link = 'Comment' },

  --NavicNamespace = {},
  --NavicPackage = {},
  --NavicString = {},
  --NavicNumber = {},
  --NavicBoolean = {},
  --NavicArray = {},
  --NavicObject = {},
  --NavicKey = {},
  --NavicNull = {},
  --NavicSeparator = {},
}
