name: Tests

on: [push, pull_request_target]

jobs:
  test-linux:
    name: Luacheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install luacheck
        run: sudo apt update -y && sudo apt upgrade -y && sudo apt install lua-check

      - name: Luacheck
        run: luacheck lua/
